// PILE BEHAVIOR
export const ADD_PILE_TO_CART = "ADD_PILE_TO_CART"
export const REMOVE_ONE_PILE_FROM_CART = "REMOVE_ONE_PILE_FROM_CART"
export const REMOVE_ALL_PILE_FROM_CART = "REMOVE_ALL_PILE_FROM_CART"

// ISOLATE BEHAVIOR
export const ADD_ISOLATE_TO_CART = "ADD_ISOLATE_TO_CART"
export const REMOVE_ISOLATE_FROM_CART = "REMOVE_ISOLATE_FROM_CART"

export const CLEAR_CART = "CLEAR_CART"
export const SET_PAYMENT_METHOD = "SET_PAYMENT"
export const VALIDATE_PAYMENT = "VALIDATE_PAYMENT"

// DB ACTIONS
export const READ_ALL_PRODUCTS = "READ_ALL_PRODUCTS"
export const READ_ALL_PAYMENT_METHODS = "READ_ALL_PAYMENT_METHODS"
export const READ_ALL_CATEGORIES = "READ_ALL_CATEGORIES"
export const NO_DATA = "NO_DATA"
